config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  
  root to: 'pages#home'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :folios, except: [:show] do
    put :sort, on: :collection
  end
  
  get 'folio/:id', to: 'folios#show', as: 'folio_show'
  get 'react-items', to: 'folios#react'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p class="app-footer"><%= copyright_generator %></p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Scott Young</h3>
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper('nav-link', 'span') %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p><%= copyright_generator %></p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">The Rambling Programmer</h1>
    <p class="lead blog-description">Random musings on programming, mostly.</p>
    <span>
      <%= link_to 'Write A New Blog', new_blog_path if logged_in?(:site_admin) %>
    </span>  
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded blog-nav">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="container">
    <%= link_to "Scott Young", root_path, class: 'navbar-brand' %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <%= nav_helper 'nav-link', 'li' %>  
        <%= login_helper 'nav-link' %>  
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
    <div class="sidebar-module sidebar-module-inset">
      <h4>About</h4>
      <p>Programmer, endurance athlete, nerd, gamer, skeptic.</p>
    </div>

    <%= source_helper("alert alert-info blog-sidebar-sources") %>

    <div class="sidebar-module">
      <h4>Topics</h4>
      <% @sidebar_topics.each do |topic| %>
        <p><%= link_to topic.title, topic_path(topic) %></p>
      <% end %>
    </div>
    
    <div class="sidebar-module">
      <h4>Elsewhere</h4>
      <ol class="list-unstyled social-links">
        <li><a href="https://github.com/SYoung82" target="_blank"><%= fa_icon "github" %></a></li>
        <li><a href="https://www.linkedin.com/in/scott-w-young/" target="_blank"><%= fa_icon "linkedin" %></a></li>
        <li><a href="https://www.facebook.com/scottyoung82" target="_blank"><%= fa_icon "facebook" %></a></li>
      </ol>
    </div>

  </div>
</div>

app/views/shared/_folio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to 'View All Portfolio Items', folios_path unless current_page?(folios_path)%> |
      <a href="#">Back to top</a>
    </p>
    <p><%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_folio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Portfolio</h1>
    <p class="lead text-muted">Code for all projects can be found on my <a href="https://www.github.com/SYoung82">github</a> page</p>
    <p>
      <%= link_to 'More About Me', about_path, class: "btn btn-primary" %>
      <%= link_to 'Blog', blogs_path, class: "btn btn-secondary" %>
    </p>
  </div>
</section>

app/views/shared/_folio_nav.html.erb
<div class="collapse bg-inverse" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 py-4">
        <h4 class="text-white">Portfolio</h4>
        <p class="text-muted">Programs and projects I'm proud to call my own.  A variety of technologies and tools are highlighted.</p>
      </div>
      <div class="col-sm-4 py-4">
        <h4 class="text-white">Navigate</h4>
        <ul class="list-unstyled">
          <%= nav_helper('text-white', 'li') %>
          <li><%= login_helper "text-white" %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="navbar navbar-inverse bg-inverse">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand">Scott Young</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "About Me", about_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
  <div><%= link_to "Blog", blogs_path %></div>
  <div><%= link_to "Portfolio", folios_path %></div>
</div>