config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  
  root to: 'pages#home'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :folios, except: [:show] do
    put :sort, on: :collection
  end
  
  get 'folio/:id', to: 'folios#show', as: 'folio_show'
  get 'react-items', to: 'folios#react'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/folio.rb
class Folio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies, allow_destroy: true,
    reject_if: lambda { |attrs| attrs['name'].blank? }

  validates_presence_of :title, :body

  mount_uploader :thumb_image, FolioUploader
  mount_uploader :main_image, FolioUploader

  def self.by_position
    order("position ASC")
  end
  
  # Same as scope below with different subtitle
  def self.react
    where(subtitle: 'React')
  end
  # These do the same thing with different subtitles
  scope :ror, -> { where(subtitle: 'Ruby On Rails')}
end

app/controllers/folios_controller.rb
class FoliosController < ApplicationController
  before_action :set_folio, only: [:edit, :show, :update, :destroy]
  layout 'folio'
  access all: [:show, :index, :react], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all

  def index
    @folio_items = Folio.by_position
  end

  def sort
    params[:order].each do |key, value|
      Folio.find(value[:id]).update(position: value[:position])
    end

    render nothing: true
  end

  def react
    @react_folio_items = Folio.react
  end
  
  def show
  end
  
  def new
    @folio_item = Folio.new
  end
  
  def create
    @folio_item = Folio.new(folio_params)

    respond_to do |format|
      if @folio_item.save
        format.html { redirect_to folios_path, notice: 'Your portfolio item is now live.' }
      else
        format.html { render :new }
      end
    end
  end
  
  def edit
  end
  
  def update
    respond_to do |format|
      if @folio_item.update(folio_params)
        format.html { redirect_to folios_path, notice: 'Portfolio was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @folio_item.destroy
    respond_to do |format|
      format.html { redirect_to folios_path, notice: 'Portfolio item was successfully destroyed.' }
    end
  end
  
  private

  def set_folio
    @folio_item = Folio.find(params[:id])
  end

  def folio_params
    params.require(:folio).permit(:title, 
                                  :subtitle, 
                                  :body, 
                                  :main_image, 
                                  :thumb_image, 
                                  technologies_attributes: [:id, :name, :_destroy])
  end
  
end

app/helpers/folios_helper.rb
module FoliosHelper
  def image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}"
  end

  def folio_img(img, type)
    if img.model.main_image? || img.model.thumb_image?
      img
    elsif type == 'thumb'
      image_generator(height: '350', width: '200')
    elsif type == 'main'
      image_generator(height: '600', width: '400')
    end
  end 
end  

app/views/folios/_folio_item.html.erb
<div class="col-md-4">
  <div class="card" data-id="<%= folio_item.id %>">
    <%= image_tag folio_img(folio_item.thumb_image, 'thumb'), width: '100%' %>
    <p class="card-text">
      <span><%= link_to folio_item.title, folio_show_path(folio_item) %></span>
      <%= folio_item.subtitle %>
    </p>
  </div>
</div>

app/views/folios/_form.html.erb
<%= form_for(@folio_item) do |f| %>
  <% if @folio_item.errors.any? %>
    <% @folio_item.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: "form-control" %>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload main image file <%= f.file_field :main_image, style: 'display:none;' %>
        </label>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload thumb image file <%= f.file_field :thumb_image, style: 'display:none;' %>
        </label>
      </div>
    </div>
 
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: "form-control", rows: 15 %>
      </div>
    </div>
  
    <div class="col-md-12">
      <h3> Technologies Used:</h3>
      <div>
        <%= f.fields_for :technologies do |technology_form| %>
          <%= render 'technology_fields', f: technology_form %>
        <% end %>

        <div>
          <%= link_to_add_association 'Add Technology', f, :technologies %>
        </div>
      </div>

      <div class="form-group">
        <%= f.submit "Submit", class: "btn btn-primary btn-block" %>
      </div>
    </div>
  
<% end %>

app/views/folios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= link_to_remove_association 'Remove Technology', f %>
</div>

app/views/folios/edit.html.erb
<div class="container folio-container"> 
  <h1>Edit this Portfolio Item</h1>

  <%= render 'form', folio_item: @folio_item %>
</div>

app/views/folios/index.html.erb
<div class="album text-muted">
  <div class="container">
    <%= source_helper("alert alert-warning") %>
    <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
      <%= render partial: 'folio_item', collection: @folio_items %>
    </div>
  </div>
</div>

app/views/folios/new.html.erb
<div class="container folio-container"> 
  <h1>Create a new Portfolio Item</h1>

  <%= render 'form', folio_item: @folio_item %>
</div>

app/views/folios/react.html.erb
<p id="notice"><%= notice %></p>

<h1>React Portfolio Items</h1>

<%= link_to "Create New Item", new_folio_path if logged_in?(:site_admin) %>

<% @react_folio_items.each do |item| %>
  <p><%= link_to item.title, folio_show_path(item) %></p>
  <p><%= item.subtitle %></p>
  <p><%= item.body %></p>
  <%= image_tag item.thumb_image unless item.thumb_image.nil? %><br/>
  <%= link_to "Edit", edit_folio_path(item) if logged_in?(:site_admin) %><br/>
  <%= link_to 'Delete Portfolio Item', folio_path(item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>
  <hr>
<% end %>

app/views/folios/show.html.erb
<div class="container folio-container">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag folio_img(@folio_item.main_image, 'main'), width: '100%' %>
    </div>

    <div class="col-md-5">
      <h1><%= @folio_item.title %></h1>
      <hr />
      <em><%= @folio_item.subtitle %></em>
      <p><%= markdown @folio_item.body %></p>
      <hr />
      <h3>Technologies Used</h3>
      <% @folio_item.technologies.each do |t| %>
        <p><%= t.name %></p>
      <% end %>
      
      <% if logged_in?(:site_admin) %>
        <div>
          <%= link_to "Edit Item", edit_folio_path(@folio_item), class:'btn btn-warning' %>
        </div>
      <% end %>
    </div>
  </div>
</div>